# Generated by Django 4.2.4 on 2023-09-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
