# Generated by Django 4.2.4 on 2023-09-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_artist_description_remove_track_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='track',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
