# Generated by Django 4.2.4 on 2023-09-21 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='artist',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
