# Generated by Django 4.2.4 on 2023-09-22 07:35

from django.db import migrations, models
import django.utils.timezone
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_create_at_album_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, height_field='10rem', upload_to=music.models.upload_to, width_field='10rem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(default=1, height_field='10rem', upload_to=music.models.upload_to, width_field='10rem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(default=1, height_field='10rem', upload_to=music.models.upload_to, width_field='10rem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.ImageField(default=1, height_field='10rem', upload_to=music.models.upload_to, width_field='10rem'),
            preserve_default=False,
        ),
    ]
