# Generated by Django 4.2.4 on 2023-09-22 07:38

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_image_artist_image_genre_image_track_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(height_field='20', upload_to=music.models.upload_to, width_field='20'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(height_field='20', upload_to=music.models.upload_to, width_field='20'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(height_field='20', upload_to=music.models.upload_to, width_field='20'),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.ImageField(height_field='20', upload_to=music.models.upload_to, width_field='20'),
        ),
    ]
