# Generated by Django 4.2.5 on 2023-09-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_remove_album_image_remove_artist_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(default='album/mario.png', upload_to='album/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='nghe-si/mario.png', upload_to='nghe-si/'),
        ),
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='the-loai/mario.png', upload_to='the-loai/'),
        ),
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.ImageField(default='bai-hat/mario.png', upload_to='bai-hat/'),
        ),
    ]
