# Generated by Django 4.2.5 on 2023-09-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_album_image_artist_image_genre_image_track_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
