# Generated by Django 4.2.5 on 2023-09-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_alter_track_lyrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='the-loai/music_disc.jpg', upload_to='the-loai/')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'area',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(default='album/music_disc.jpg', upload_to='album/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='nghe-si/music_disc.jpg', upload_to='nghe-si/'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='the-loai/music_disc.jpg', upload_to='the-loai/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.ImageField(default='bai-hat/music_disc.jpg', upload_to='bai-hat/'),
        ),
    ]
