# Generated by Django 4.2.5 on 2023-09-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_area_alter_album_image_alter_artist_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.area'),
            preserve_default=False,
        ),
    ]
