# Generated by Django 4.2.5 on 2023-09-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_genre_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.area'),
        ),
        migrations.AddField(
            model_name='artist',
            name='follows',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='area',
            name='image',
            field=models.ImageField(default='khu-vuc/music_disc.jpg', upload_to='khu-vuc/'),
        ),
    ]
