# Generated by Django 4.2.5 on 2023-09-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_artist_area_artist_follows_alter_area_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='streams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='favorites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='streams',
            field=models.IntegerField(default=0),
        ),
    ]
