# Generated by Django 4.2.5 on 2023-10-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_album_favorites_album_streams_track_favorites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.URLField(default='https://www.youtube.com/watch?v=Ora2P-xjPgA'),
        ),
    ]
