# Generated by Django 4.2.5 on 2023-10-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_track_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_follow',
            field=models.BooleanField(default=False),
        ),
    ]
