# Generated by Django 4.2.5 on 2023-10-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_artist_is_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_trend',
            field=models.BooleanField(default=False),
        ),
    ]
