# Generated by Django 4.2.5 on 2023-10-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_track_is_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='top_trend',
            field=models.IntegerField(default=-1),
        ),
    ]
