# Generated by Django 4.2.5 on 2023-10-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_remove_artist_is_follow_userartist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userartist',
            name='is_follow',
        ),
    ]
